// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/monitor/v1/user_notification.proto

package monitor_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserNotification struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NotificationId       int64    `protobuf:"varint,3,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	MethodKind           string   `protobuf:"bytes,6,opt,name=method_kind,json=methodKind,proto3" json:"method_kind,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,9,opt,name=code,proto3" json:"code,omitempty"`
	ApiKey               string   `protobuf:"bytes,10,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Enabled              bool     `protobuf:"varint,11,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNotification) Reset()         { *m = UserNotification{} }
func (m *UserNotification) String() string { return proto.CompactTextString(m) }
func (*UserNotification) ProtoMessage()    {}
func (*UserNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{0}
}

func (m *UserNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotification.Unmarshal(m, b)
}
func (m *UserNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotification.Marshal(b, m, deterministic)
}
func (m *UserNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotification.Merge(m, src)
}
func (m *UserNotification) XXX_Size() int {
	return xxx_messageInfo_UserNotification.Size(m)
}
func (m *UserNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotification.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotification proto.InternalMessageInfo

func (m *UserNotification) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserNotification) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserNotification) GetNotificationId() int64 {
	if m != nil {
		return m.NotificationId
	}
	return 0
}

func (m *UserNotification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UserNotification) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UserNotification) GetMethodKind() string {
	if m != nil {
		return m.MethodKind
	}
	return ""
}

func (m *UserNotification) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserNotification) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserNotification) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *UserNotification) GetApiKey() string {
	if m != nil {
		return m.ApiKey
	}
	return ""
}

func (m *UserNotification) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type ListUserNotificationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserNotificationsRequest) Reset()         { *m = ListUserNotificationsRequest{} }
func (m *ListUserNotificationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserNotificationsRequest) ProtoMessage()    {}
func (*ListUserNotificationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{1}
}

func (m *ListUserNotificationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserNotificationsRequest.Unmarshal(m, b)
}
func (m *ListUserNotificationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserNotificationsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserNotificationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserNotificationsRequest.Merge(m, src)
}
func (m *ListUserNotificationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserNotificationsRequest.Size(m)
}
func (m *ListUserNotificationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserNotificationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserNotificationsRequest proto.InternalMessageInfo

type ListUserNotificationsResponse struct {
	UserNotifications    []*UserNotification `protobuf:"bytes,1,rep,name=userNotifications,proto3" json:"userNotifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ListUserNotificationsResponse) Reset()         { *m = ListUserNotificationsResponse{} }
func (m *ListUserNotificationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserNotificationsResponse) ProtoMessage()    {}
func (*ListUserNotificationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{2}
}

func (m *ListUserNotificationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserNotificationsResponse.Unmarshal(m, b)
}
func (m *ListUserNotificationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserNotificationsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserNotificationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserNotificationsResponse.Merge(m, src)
}
func (m *ListUserNotificationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserNotificationsResponse.Size(m)
}
func (m *ListUserNotificationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserNotificationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserNotificationsResponse proto.InternalMessageInfo

func (m *ListUserNotificationsResponse) GetUserNotifications() []*UserNotification {
	if m != nil {
		return m.UserNotifications
	}
	return nil
}

type GetUserNotificationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserNotificationRequest) Reset()         { *m = GetUserNotificationRequest{} }
func (m *GetUserNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserNotificationRequest) ProtoMessage()    {}
func (*GetUserNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{3}
}

func (m *GetUserNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNotificationRequest.Unmarshal(m, b)
}
func (m *GetUserNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNotificationRequest.Marshal(b, m, deterministic)
}
func (m *GetUserNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNotificationRequest.Merge(m, src)
}
func (m *GetUserNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserNotificationRequest.Size(m)
}
func (m *GetUserNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNotificationRequest proto.InternalMessageInfo

func (m *GetUserNotificationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateUserNotificationRequest struct {
	UserNotification     *UserNotification `protobuf:"bytes,1,opt,name=userNotification,proto3" json:"userNotification,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateUserNotificationRequest) Reset()         { *m = CreateUserNotificationRequest{} }
func (m *CreateUserNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserNotificationRequest) ProtoMessage()    {}
func (*CreateUserNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{4}
}

func (m *CreateUserNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserNotificationRequest.Unmarshal(m, b)
}
func (m *CreateUserNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserNotificationRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserNotificationRequest.Merge(m, src)
}
func (m *CreateUserNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserNotificationRequest.Size(m)
}
func (m *CreateUserNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserNotificationRequest proto.InternalMessageInfo

func (m *CreateUserNotificationRequest) GetUserNotification() *UserNotification {
	if m != nil {
		return m.UserNotification
	}
	return nil
}

type UpdateUserNotificationRequest struct {
	UserNotification     *UserNotification     `protobuf:"bytes,1,opt,name=userNotification,proto3" json:"userNotification,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserNotificationRequest) Reset()         { *m = UpdateUserNotificationRequest{} }
func (m *UpdateUserNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserNotificationRequest) ProtoMessage()    {}
func (*UpdateUserNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{5}
}

func (m *UpdateUserNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserNotificationRequest.Unmarshal(m, b)
}
func (m *UpdateUserNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserNotificationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserNotificationRequest.Merge(m, src)
}
func (m *UpdateUserNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserNotificationRequest.Size(m)
}
func (m *UpdateUserNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserNotificationRequest proto.InternalMessageInfo

func (m *UpdateUserNotificationRequest) GetUserNotification() *UserNotification {
	if m != nil {
		return m.UserNotification
	}
	return nil
}

func (m *UpdateUserNotificationRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeleteUserNotificationRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserNotificationRequest) Reset()         { *m = DeleteUserNotificationRequest{} }
func (m *DeleteUserNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserNotificationRequest) ProtoMessage()    {}
func (*DeleteUserNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c7f3c65f381bd5f, []int{6}
}

func (m *DeleteUserNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserNotificationRequest.Unmarshal(m, b)
}
func (m *DeleteUserNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserNotificationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserNotificationRequest.Merge(m, src)
}
func (m *DeleteUserNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserNotificationRequest.Size(m)
}
func (m *DeleteUserNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserNotificationRequest proto.InternalMessageInfo

func (m *DeleteUserNotificationRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*UserNotification)(nil), "monitor.v1.UserNotification")
	proto.RegisterType((*ListUserNotificationsRequest)(nil), "monitor.v1.ListUserNotificationsRequest")
	proto.RegisterType((*ListUserNotificationsResponse)(nil), "monitor.v1.ListUserNotificationsResponse")
	proto.RegisterType((*GetUserNotificationRequest)(nil), "monitor.v1.GetUserNotificationRequest")
	proto.RegisterType((*CreateUserNotificationRequest)(nil), "monitor.v1.CreateUserNotificationRequest")
	proto.RegisterType((*UpdateUserNotificationRequest)(nil), "monitor.v1.UpdateUserNotificationRequest")
	proto.RegisterType((*DeleteUserNotificationRequest)(nil), "monitor.v1.DeleteUserNotificationRequest")
}

func init() {
	proto.RegisterFile("proto/monitor/v1/user_notification.proto", fileDescriptor_1c7f3c65f381bd5f)
}

var fileDescriptor_1c7f3c65f381bd5f = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x93, 0x36, 0x69, 0xc7, 0x52, 0x09, 0x2b, 0x24, 0x56, 0x51, 0x03, 0x96, 0x2f, 0xf8,
	0x80, 0x6c, 0xb5, 0x1c, 0x39, 0x82, 0x80, 0x52, 0xe0, 0x60, 0xa9, 0x67, 0x6b, 0xd3, 0x9d, 0xb4,
	0x23, 0xdb, 0xbb, 0xc6, 0xbb, 0xae, 0xd4, 0xbf, 0xe1, 0xc4, 0x77, 0x22, 0x8f, 0x1b, 0x11, 0x39,
	0x8a, 0xb8, 0x71, 0x9b, 0x79, 0xf3, 0xe6, 0xbd, 0xb1, 0xf7, 0x41, 0xd2, 0xb4, 0xd6, 0xdb, 0xac,
	0xb6, 0x86, 0xbc, 0x6d, 0xb3, 0x87, 0x8b, 0xac, 0x73, 0xd8, 0x16, 0xc6, 0x7a, 0xda, 0xd0, 0xad,
	0xf2, 0x64, 0x4d, 0xca, 0x14, 0x01, 0x4f, 0x9c, 0xf4, 0xe1, 0x62, 0x19, 0xdd, 0x59, 0x7b, 0x57,
	0x61, 0xc6, 0x93, 0x75, 0xb7, 0xc9, 0x36, 0x84, 0x95, 0x2e, 0x6a, 0xe5, 0xca, 0x81, 0x1d, 0xff,
	0x9a, 0xc0, 0xe2, 0xc6, 0x61, 0xfb, 0x63, 0x47, 0x48, 0x9c, 0xc1, 0x84, 0xb4, 0x0c, 0xa2, 0x20,
	0x99, 0xe6, 0x13, 0xd2, 0xe2, 0x25, 0xcc, 0xd9, 0x8d, 0xb4, 0x9c, 0x30, 0x38, 0xeb, 0xdb, 0x2b,
	0x2d, 0xde, 0xc0, 0xb3, 0xdd, 0x0b, 0x7a, 0xc2, 0x94, 0x09, 0x67, 0xbb, 0xf0, 0x95, 0x16, 0x2f,
	0xe0, 0xd8, 0x93, 0xaf, 0x50, 0x1e, 0x45, 0x41, 0x72, 0x9a, 0x0f, 0x8d, 0x58, 0xc0, 0xb4, 0x6b,
	0x2b, 0x79, 0xcc, 0x58, 0x5f, 0x8a, 0xd7, 0x10, 0xd6, 0xe8, 0xef, 0xad, 0x2e, 0x4a, 0x32, 0x5a,
	0xce, 0x78, 0x02, 0x03, 0x74, 0x4d, 0x86, 0x85, 0x9a, 0x7b, 0x6b, 0x50, 0xce, 0x07, 0x21, 0x6e,
	0x7a, 0x14, 0x6b, 0x45, 0x95, 0x3c, 0x19, 0x50, 0x6e, 0x84, 0x80, 0xa3, 0x5b, 0xab, 0x51, 0x9e,
	0x32, 0xc8, 0x75, 0xff, 0x29, 0xaa, 0xa1, 0xa2, 0xc4, 0x47, 0x09, 0x0c, 0xcf, 0x54, 0x43, 0xd7,
	0xf8, 0x28, 0x24, 0xcc, 0xd1, 0xa8, 0x75, 0x85, 0x5a, 0x86, 0x51, 0x90, 0x9c, 0xe4, 0xdb, 0x36,
	0x7e, 0x05, 0xe7, 0xdf, 0xc8, 0xf9, 0xf1, 0x5f, 0x72, 0x39, 0xfe, 0xec, 0xd0, 0xf9, 0xb8, 0x84,
	0xd5, 0x81, 0xb9, 0x6b, 0xac, 0x71, 0x28, 0xbe, 0xc2, 0xf3, 0x6e, 0x3c, 0x94, 0x41, 0x34, 0x4d,
	0xc2, 0xcb, 0xf3, 0xf4, 0xef, 0x6b, 0xa5, 0x63, 0x85, 0x7c, 0x7f, 0x2d, 0x7e, 0x0b, 0xcb, 0xcf,
	0xb8, 0xe7, 0xf5, 0x74, 0xca, 0xf8, 0xe1, 0x62, 0x82, 0xd5, 0x87, 0x16, 0x95, 0xc7, 0x43, 0x0b,
	0x5f, 0x60, 0x31, 0xf6, 0xe0, 0xf5, 0x7f, 0x5d, 0xb6, 0xb7, 0x15, 0xff, 0x0e, 0x60, 0x75, 0xd3,
	0xe8, 0xff, 0xe1, 0x25, 0xde, 0x43, 0xd8, 0xb1, 0x15, 0x27, 0x99, 0x33, 0x19, 0x5e, 0x2e, 0xd3,
	0x21, 0xec, 0xe9, 0x36, 0xec, 0xe9, 0xa7, 0x3e, 0xec, 0xdf, 0x95, 0x2b, 0x73, 0x18, 0xe8, 0x7d,
	0x1d, 0x67, 0xb0, 0xfa, 0x88, 0x15, 0x1e, 0xbe, 0x73, 0xf4, 0x13, 0xd7, 0x33, 0x16, 0x7c, 0xf7,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x3e, 0x54, 0x79, 0x83, 0x03, 0x00, 0x00,
}
